#!/usr/bin/env bash
# This script prints "Best School" 10 times, and "Hi" after the 9th time
counter=1
while [ $counter -le 10 ]
do
    echo "Best School"
    if [ $counter -eq 9 ]
    then
        echo "Hi"
    fi
    ((counter++))
done
